import type {
  Endpoint,
  InitialTableEntryTemplate,
  ScenarioDay,
  ScenarioPacket,
  StampDefinition,
  StampId,
  TableColumnKey,
  TransportProtocol,
} from './types';

export const HOME_LABEL = '自宅';

export const TABLE_COLUMN_LABELS: Record<TableColumnKey, string> = {
  protocol: 'Proto',
  externalHost: '外側',
  externalPort: '色',
  destinationHost: '宛先',
  destinationService: 'サービス',
  internalHost: '内側',
  internalPort: '内側Port',
};

export const STAMP_DEFINITIONS: Record<StampId, StampDefinition> = {
  home: {
    id: 'home',
    label: '自宅',
    chipClassName: 'bg-stone-100 text-stone-800 border-stone-300',
    buttonClassName: 'border-stone-400 bg-stone-500/15 text-stone-100 hover:bg-stone-500/25',
  },
  red: {
    id: 'red',
    label: '赤',
    chipClassName: 'bg-red-100 text-red-800 border-red-300',
    buttonClassName: 'border-red-400 bg-red-500/15 text-red-100 hover:bg-red-500/25',
  },
  blue: {
    id: 'blue',
    label: '青',
    chipClassName: 'bg-blue-100 text-blue-800 border-blue-300',
    buttonClassName: 'border-blue-400 bg-blue-500/15 text-blue-100 hover:bg-blue-500/25',
  },
  green: {
    id: 'green',
    label: '緑',
    chipClassName: 'bg-green-100 text-green-800 border-green-300',
    buttonClassName: 'border-green-400 bg-green-500/15 text-green-100 hover:bg-green-500/25',
  },
  yellow: {
    id: 'yellow',
    label: '黄',
    chipClassName: 'bg-yellow-100 text-yellow-800 border-yellow-300',
    buttonClassName: 'border-yellow-400 bg-yellow-500/15 text-yellow-100 hover:bg-yellow-500/25',
  },
  orange: {
    id: 'orange',
    label: '橙',
    chipClassName: 'bg-orange-100 text-orange-800 border-orange-300',
    buttonClassName: 'border-orange-400 bg-orange-500/15 text-orange-100 hover:bg-orange-500/25',
  },
  purple: {
    id: 'purple',
    label: '紫',
    chipClassName: 'bg-violet-100 text-violet-800 border-violet-300',
    buttonClassName: 'border-violet-400 bg-violet-500/15 text-violet-100 hover:bg-violet-500/25',
  },
  cyan: {
    id: 'cyan',
    label: '水',
    chipClassName: 'bg-cyan-100 text-cyan-800 border-cyan-300',
    buttonClassName: 'border-cyan-400 bg-cyan-500/15 text-cyan-100 hover:bg-cyan-500/25',
  },
  pink: {
    id: 'pink',
    label: '桃',
    chipClassName: 'bg-pink-100 text-pink-800 border-pink-300',
    buttonClassName: 'border-pink-400 bg-pink-500/15 text-pink-100 hover:bg-pink-500/25',
  },
  lime: {
    id: 'lime',
    label: '若緑',
    chipClassName: 'bg-lime-100 text-lime-800 border-lime-300',
    buttonClassName: 'border-lime-400 bg-lime-500/15 text-lime-100 hover:bg-lime-500/25',
  },
  amber: {
    id: 'amber',
    label: '琥珀',
    chipClassName: 'bg-amber-100 text-amber-800 border-amber-300',
    buttonClassName: 'border-amber-400 bg-amber-500/15 text-amber-100 hover:bg-amber-500/25',
  },
  teal: {
    id: 'teal',
    label: '青緑',
    chipClassName: 'bg-teal-100 text-teal-800 border-teal-300',
    buttonClassName: 'border-teal-400 bg-teal-500/15 text-teal-100 hover:bg-teal-500/25',
  },
  indigo: {
    id: 'indigo',
    label: '藍',
    chipClassName: 'bg-indigo-100 text-indigo-800 border-indigo-300',
    buttonClassName: 'border-indigo-400 bg-indigo-500/15 text-indigo-100 hover:bg-indigo-500/25',
  },
  rose: {
    id: 'rose',
    label: '薔薇',
    chipClassName: 'bg-rose-100 text-rose-800 border-rose-300',
    buttonClassName: 'border-rose-400 bg-rose-500/15 text-rose-100 hover:bg-rose-500/25',
  },
  sky: {
    id: 'sky',
    label: '空',
    chipClassName: 'bg-sky-100 text-sky-800 border-sky-300',
    buttonClassName: 'border-sky-400 bg-sky-500/15 text-sky-100 hover:bg-sky-500/25',
  },
  emerald: {
    id: 'emerald',
    label: '翠',
    chipClassName: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    buttonClassName: 'border-emerald-400 bg-emerald-500/15 text-emerald-100 hover:bg-emerald-500/25',
  },
  slate: {
    id: 'slate',
    label: '灰',
    chipClassName: 'bg-slate-100 text-slate-800 border-slate-300',
    buttonClassName: 'border-slate-400 bg-slate-500/15 text-slate-100 hover:bg-slate-500/25',
  },
};

const ALL_STAMP_IDS = Object.keys(STAMP_DEFINITIONS) as StampId[];
export const PORT_STAMP_IDS = ALL_STAMP_IDS.filter((stampId) => stampId !== 'home') as Exclude<StampId, 'home'>[];

const endpoint = (host: string, port?: string): Endpoint => ({ host, port });

const backgroundFlow = (
  minPackets: number,
  maxPackets: number,
  options?: {
    firstDelayActions?: number;
    intervalActions?: number;
    queuePosition?: 'front' | 'back';
    waitBudgetActions?: number;
    prompt?: string;
    note?: string;
  },
): NonNullable<InitialTableEntryTemplate['backgroundFlow']> => ({
  minPackets,
  maxPackets,
  ...options,
});

const seededEntry = (
  externalPort: StampId,
  internalHost: string,
  destinationHost: string,
  destinationService: string,
  remainingTurns: number,
  protocol: TransportProtocol = 'TCP',
  internalPort?: string,
): InitialTableEntryTemplate => ({
  protocol,
  externalHost: HOME_LABEL,
  externalPort,
  destinationHost,
  destinationService,
  internalHost,
  internalPort,
  lifecycleState: 'active',
  remainingTurns,
});

const repeatGroup = (
  copyGroup: string,
  minCopies: number,
  maxCopies: number,
): ScenarioPacket['runtime'] => ({
  copyGroup,
  minCopies,
  maxCopies,
});

const oncePerSession = (runtime?: ScenarioPacket['runtime']): ScenarioPacket['runtime'] => ({
  ...runtime,
  spawnTiming: 'oncePerSession',
});

const optionalTraffic = (
  spawnChance: number,
  runtime?: ScenarioPacket['runtime'],
): ScenarioPacket['runtime'] => ({
  ...runtime,
  spawnChance,
});

const variantTraffic = (
  variantGroup: string,
  variantId: string,
  runtime?: ScenarioPacket['runtime'],
): ScenarioPacket['runtime'] => ({
  ...runtime,
  variantGroup,
  variantId,
});

const packet = (
  id: string,
  direction: ScenarioPacket['packet']['direction'],
  source: Endpoint,
  destination: Endpoint,
  prompt: string,
  expectation: ScenarioPacket['expectation'],
  note?: string,
  protocol?: TransportProtocol,
  forcedFailure?: ScenarioPacket['forcedFailure'],
  runtime?: ScenarioPacket['runtime'],
): ScenarioPacket => ({
  id,
  prompt,
  expectation,
  forcedFailure,
  runtime,
  packet: {
    id,
    direction,
    source,
    destination,
    protocol,
    note,
  },
});

export const scenarioDays: ScenarioDay[] = [
  {
    id: 'day-1',
    unit: 1,
    dayNumber: 1,
    phaseId: 'directRouting',
    title: 'DAY 1: 送る / 戻す',
    summary: 'まずは個包を受け取り、宛先札を当てて左右へ流す基本操作を覚える。',
    learningGoal: '個包は受取口から机へ出し、宛先を決めてから送る。',
    availableStamps: [],
    availableVerdicts: ['ACCEPT'],
    rules: {
      columns: [],
      inboundLookupKeys: [],
    },
    runtime: {
      ordering: 'grouped',
      repeatForcedFailureUntilIncident: false,
      minCycles: 1,
      maxCycles: 1,
      varianceMode: 'intro',
    },
    packets: [
      {
        ...packet(
          'day-1-outbound',
          'lanToWan',
          endpoint('PC-A'),
          endpoint('Server-1'),
          'Server-1 の札を個包に重ねて、右へ通す。',
          { verdict: 'ACCEPT', flow: 'outbound' },
          undefined,
          undefined,
          undefined,
          repeatGroup('day-1-main', 1, 1),
        ),
        routeTargets: [endpoint('Server-1'), endpoint('Server-2')],
        responsePlan: {
          prompt: 'PC-A の札を個包に重ねて、左へ戻す。',
          routeTargets: [endpoint('PC-A'), endpoint('PC-B')],
          queuePosition: 'front',
        },
      },
    ],
  },
  {
    id: 'day-2',
    unit: 1,
    dayNumber: 2,
    phaseId: 'natBasics',
    title: 'DAY 2: NATの破綻',
    summary: '送信元を自宅へ書き換える NAT を覚え、その直後に同時通信で破綻する。',
    learningGoal: '単純な NAT だけでは同時通信を一意に戻せない。',
    availableStamps: ['home'],
    availableVerdicts: ['ACCEPT'],
    rules: {
      columns: ['externalHost', 'internalHost'],
      inboundLookupKeys: ['externalHost'],
    },
    runtime: {
      ordering: 'grouped',
      repeatForcedFailureUntilIncident: false,
      minCycles: 1,
      maxCycles: 1,
      varianceMode: 'intro',
    },
    packets: [
      {
        ...packet(
          'day-2-outbound-a',
          'lanToWan',
          endpoint('PC-A'),
          endpoint('Server-1'),
          'PC-A の送信元を「自宅」に書き換えて外へ通す。',
          { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'home' },
        ),
        responsePlan: {
          prompt: 'テーブルを見て、返信を内側へ戻す。',
          queuePosition: 'back',
          delayActions: 2,
          forcedFailure: {
            title: '仕様破綻',
            message:
              '同じ「自宅」に PC-A と PC-B がぶら下がっているため、返信先を一意に決められません。ここで外側ポートが必要になります。',
          },
        },
      },
      packet(
        'day-2-outbound-b',
        'lanToWan',
        endpoint('PC-B'),
        endpoint('Server-1'),
        'PC-B も同じく「自宅」として外へ出す。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'home' },
      ),
    ],
  },
  {
    id: 'day-3',
    unit: 1,
    dayNumber: 3,
    phaseId: 'portStamp',
    title: 'DAY 3: 色スタンプ導入',
    summary: '外側ポートを色スタンプとして導入し、戻り先を区別できるようにする。',
    learningGoal: '外側ポートが加わると同じ自宅でも通信を分けられる。',
    availableStamps: ['red', 'blue'],
    availableVerdicts: ['ACCEPT'],
    rules: {
      columns: ['externalHost', 'externalPort', 'internalHost'],
      inboundLookupKeys: ['externalHost', 'externalPort'],
    },
    packets: [
      {
        ...packet(
          'day-3-outbound-a',
          'lanToWan',
          endpoint('PC-A'),
          endpoint('Server-1'),
          'PC-A には赤スタンプを割り当てる。',
          { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
          undefined,
          undefined,
          undefined,
          repeatGroup('day-3-a', 1, 3),
        ),
        responsePlan: {
          prompt: '赤の返信は PC-A に戻す。',
          queuePosition: 'front',
          delayActions: 2,
        },
      },
      {
        ...packet(
          'day-3-outbound-b',
          'lanToWan',
          endpoint('PC-B'),
          endpoint('Server-1'),
          'PC-B には青スタンプを割り当てる。',
          { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'blue' },
          undefined,
          undefined,
          undefined,
          repeatGroup('day-3-b', 1, 3),
        ),
        responsePlan: {
          prompt: '青の返信は PC-B に戻す。',
          queuePosition: 'front',
          delayActions: 1,
        },
      },
    ],
  },
  {
    id: 'day-4',
    unit: 1,
    dayNumber: 4,
    phaseId: 'portStamp',
    title: 'DAY 4: REJECTの導入',
    summary: 'テーブルに存在しない外からの通信を拒否する。',
    learningGoal: '戻り通信でも、記録のないものは通してはいけない。',
    availableStamps: ['red'],
    availableVerdicts: ['ACCEPT', 'REJECT'],
    rules: {
      columns: ['externalHost', 'externalPort', 'internalHost'],
      inboundLookupKeys: ['externalHost', 'externalPort'],
    },
    packets: [
      {
        ...packet(
          'day-4-outbound-a',
          'lanToWan',
          endpoint('PC-A'),
          endpoint('Server-1'),
          'PC-A に赤スタンプを割り当てる。',
          { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
          undefined,
          undefined,
          undefined,
          repeatGroup('day-4-main', 1, 2),
        ),
        responsePlan: {
          prompt: '赤の返信はテーブルに従って PC-A へ戻す。',
          queuePosition: 'front',
          delayActions: 2,
        },
      },
      packet(
        'day-4-inbound-bad',
        'wanToLan',
        endpoint('Unknown'),
        endpoint(HOME_LABEL, 'blue'),
        'テーブルにない通信は拒否する。',
        { verdict: 'REJECT', reason: '要求記録のない外部通信だから。', reasonCode: 'unknownInbound' },
        undefined,
        undefined,
        undefined,
        { ...repeatGroup('day-4-reject', 1, 3), arrivalDelayActions: 1 },
      ),
    ],
  },
  {
    id: 'day-5',
    unit: 2,
    dayNumber: 5,
    phaseId: 'portStamp',
    title: 'DAY 5: 色枯渇',
    summary: '色だけで区別すると、同時通信数が増えた時に色が足りなくなる。',
    learningGoal: '外側ポートだけでは規模が大きくなると破綻する。',
    availableStamps: ALL_STAMP_IDS,
    rules: {
      columns: ['externalPort', 'internalHost'],
      inboundLookupKeys: ['externalPort'],
    },
    runtime: {
      ordering: 'mixed',
      repeatForcedFailureUntilIncident: true,
      varianceMode: 'steady',
    },
    packets: [
      ...Array.from({ length: ALL_STAMP_IDS.length }, (_, index) => {
        const stampId = ALL_STAMP_IDS[index];
        const number = index + 1;
        return packet(
          `day-5-outbound-${number}`,
          'lanToWan',
          endpoint(`PC-${number}`),
          endpoint(`Server-${number}`),
          `${STAMP_DEFINITIONS[stampId].label}スタンプを割り当てる。`,
          { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: stampId },
        );
      }),
      packet(
        'day-5-collapse',
        'lanToWan',
        endpoint('PC-17'),
        endpoint('Server-1'),
        '17本目の通信だが、新しい色を割り当てられない。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        '空き色がない状態を示すイベントです。',
        undefined,
        {
          title: '色不足',
          message:
            '利用できる色は16個しかありません。外側ポートだけを識別子にしているため、17本目の通信を安全に増やせません。',
        },
      ),
    ],
  },
  {
    id: 'day-6',
    unit: 2,
    dayNumber: 6,
    phaseId: 'destinationHost',
    title: 'DAY 6: 宛先列の追加',
    summary: '宛先を記録すると、同じ色でも相手が違えば再利用できる。',
    learningGoal: '識別キーに宛先を加えると色を使い回せる。',
    availableStamps: ['red'],
    rules: {
      columns: ['externalPort', 'destinationHost', 'internalHost'],
      inboundLookupKeys: ['externalPort', 'destinationHost'],
    },
    runtime: {
      ordering: 'mixed',
      repeatForcedFailureUntilIncident: true,
      varianceMode: 'steady',
    },
    packets: [
      packet(
        'day-6-outbound-a',
        'lanToWan',
        endpoint('PC-A'),
        endpoint('Server-1'),
        'PC-A と Server-1 の通信に赤を使う。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-6-a', 1, 3),
      ),
      packet(
        'day-6-outbound-b',
        'lanToWan',
        endpoint('PC-B'),
        endpoint('Server-2'),
        '宛先が違うので、同じ赤を再利用する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-6-b', 1, 3),
      ),
      packet(
        'day-6-inbound-a',
        'wanToLan',
        endpoint('Server-1'),
        endpoint(HOME_LABEL, 'red'),
        '赤かつ宛先 Server-1 の行から PC-A を選ぶ。',
        { verdict: 'ACCEPT', flow: 'inbound', expectedTarget: endpoint('PC-A') },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-6-a', 1, 3),
      ),
      packet(
        'day-6-inbound-b',
        'wanToLan',
        endpoint('Server-2'),
        endpoint(HOME_LABEL, 'red'),
        '赤でも宛先 Server-2 なら PC-B に戻す。',
        { verdict: 'ACCEPT', flow: 'inbound', expectedTarget: endpoint('PC-B') },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-6-b', 1, 3),
      ),
    ],
  },
  {
    id: 'day-7',
    unit: 2,
    dayNumber: 7,
    phaseId: 'destinationHost',
    title: 'DAY 7: 宛先不一致の拒否',
    summary: '色が同じでも、宛先が一致しなければ通してはいけない。',
    learningGoal: '戻り通信は色だけでなく宛先でも照合する。',
    availableStamps: ['red'],
    rules: {
      columns: ['externalPort', 'destinationHost', 'internalHost'],
      inboundLookupKeys: ['externalPort', 'destinationHost'],
    },
    packets: [
      packet(
        'day-7-outbound-a',
        'lanToWan',
        endpoint('PC-A'),
        endpoint('Server-1'),
        'PC-A と Server-1 の通信を赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-7-main', 1, 2),
      ),
      packet(
        'day-7-inbound-bad',
        'wanToLan',
        endpoint('Server-2'),
        endpoint(HOME_LABEL, 'red'),
        '色は同じでも、宛先 Server-2 は要求していないので拒否する。',
        { verdict: 'REJECT', reason: '宛先がテーブルの記録と一致しないから。', reasonCode: 'destinationHostMismatch' },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-7-reject', 1, 3),
      ),
    ],
  },
  {
    id: 'day-8',
    unit: 3,
    dayNumber: 8,
    phaseId: 'destinationHost',
    title: 'DAY 8: サービス未区別の破綻',
    summary: '同じ宛先でもサービスが違うと、宛先ホストだけでは戻り先を決められない。',
    learningGoal: '宛先ホストだけでは Web と Game を区別できない。',
    availableStamps: ['red'],
    rules: {
      columns: ['externalPort', 'destinationHost', 'internalHost'],
      inboundLookupKeys: ['externalPort', 'destinationHost'],
    },
    packets: [
      packet(
        'day-8-outbound-web',
        'lanToWan',
        endpoint('PC-A'),
        endpoint('Server-1', 'Web'),
        'Server-1:Web 向けの通信を赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
      ),
      packet(
        'day-8-outbound-game',
        'lanToWan',
        endpoint('PC-B'),
        endpoint('Server-1', 'Game'),
        '同じ Server-1 だがサービス違いの通信も赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
      ),
      packet(
        'day-8-collapse',
        'wanToLan',
        endpoint('Server-1', 'Web'),
        endpoint(HOME_LABEL, 'red'),
        '返信は来たが、サービスを見ないのでどちらの通信か区別できない。',
        {
          verdict: 'ACCEPT',
          flow: 'inbound',
          expectedTarget: endpoint('PC-A'),
        },
        'サービス列がない状態では、同じ宛先ホストの通信が重なる。',
        undefined,
        {
          title: 'サービス未区別',
          message:
            '赤と Server-1 までは一致しますが、Web と Game を見分ける列がありません。宛先ポートを識別キーに追加する必要があります。',
        },
      ),
    ],
  },
  {
    id: 'day-9',
    unit: 3,
    dayNumber: 9,
    phaseId: 'destinationService',
    title: 'DAY 9: サービス列の追加',
    summary: '宛先ポートまで記録すると、同じ宛先ホストでもサービスごとに区別できる。',
    learningGoal: '宛先サービスを見れば同じ相手でも別通信として扱える。',
    availableStamps: ['red'],
    rules: {
      columns: ['externalPort', 'destinationHost', 'destinationService', 'internalHost'],
      inboundLookupKeys: ['externalPort', 'destinationHost', 'destinationService'],
    },
    runtime: {
      ordering: 'mixed',
      repeatForcedFailureUntilIncident: true,
      varianceMode: 'steady',
    },
    packets: [
      packet(
        'day-9-outbound-web',
        'lanToWan',
        endpoint('PC-A'),
        endpoint('Server-1', 'Web'),
        'Server-1:Web を赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-9-web', 1, 3),
      ),
      packet(
        'day-9-outbound-game',
        'lanToWan',
        endpoint('PC-B'),
        endpoint('Server-1', 'Game'),
        'Server-1:Game も同じ赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-9-game', 1, 3),
      ),
      packet(
        'day-9-inbound-web',
        'wanToLan',
        endpoint('Server-1', 'Web'),
        endpoint(HOME_LABEL, 'red'),
        '赤かつ Server-1:Web の行から PC-A を選ぶ。',
        { verdict: 'ACCEPT', flow: 'inbound', expectedTarget: endpoint('PC-A') },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-9-web', 1, 3),
      ),
      packet(
        'day-9-inbound-game',
        'wanToLan',
        endpoint('Server-1', 'Game'),
        endpoint(HOME_LABEL, 'red'),
        '赤かつ Server-1:Game の行から PC-B を選ぶ。',
        { verdict: 'ACCEPT', flow: 'inbound', expectedTarget: endpoint('PC-B') },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-9-game', 1, 3),
      ),
    ],
  },
  {
    id: 'day-10',
    unit: 3,
    dayNumber: 10,
    phaseId: 'destinationService',
    title: 'DAY 10: サービス不一致の拒否',
    summary: '色と宛先ホストが同じでも、サービスが一致しない返信は通してはいけない。',
    learningGoal: '戻り通信はサービスまで一致した時だけ受け入れる。',
    availableStamps: ['red'],
    rules: {
      columns: ['externalPort', 'destinationHost', 'destinationService', 'internalHost'],
      inboundLookupKeys: ['externalPort', 'destinationHost', 'destinationService'],
    },
    packets: [
      packet(
        'day-10-outbound-web',
        'lanToWan',
        endpoint('PC-A'),
        endpoint('Server-1', 'Web'),
        'Web 向けの通信を赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-10-main', 1, 2),
      ),
      packet(
        'day-10-inbound-bad',
        'wanToLan',
        endpoint('Server-1', 'Game'),
        endpoint(HOME_LABEL, 'red'),
        '色は同じでも Game は要求していないので拒否する。',
        { verdict: 'REJECT', reason: 'サービスがテーブル記録と一致しないから。', reasonCode: 'destinationServiceMismatch' },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-10-reject', 1, 3),
      ),
    ],
  },
  {
    id: 'day-11',
    unit: 4,
    dayNumber: 11,
    phaseId: 'internalPort',
    title: 'DAY 11: 内側アプリ未区別の破綻',
    summary: 'PC-A までは分かっても、どのアプリへ戻すかは内側ポートがないと決められない。',
    learningGoal: '戻り先は PC だけでなく内側ポートまで必要になる。',
    availableStamps: ['red', 'blue'],
    rules: {
      columns: ['externalPort', 'destinationHost', 'destinationService', 'internalHost'],
      inboundLookupKeys: ['externalPort', 'destinationHost', 'destinationService'],
    },
    packets: [
      packet(
        'day-11-outbound-1001',
        'lanToWan',
        endpoint('PC-A', '1001'),
        endpoint('Server-1', 'Web'),
        'PC-A:1001 の通信を赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
      ),
      packet(
        'day-11-outbound-1002',
        'lanToWan',
        endpoint('PC-A', '1002'),
        endpoint('Server-2', 'Web'),
        'PC-A:1002 の通信を青で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'blue' },
      ),
      packet(
        'day-11-collapse',
        'wanToLan',
        endpoint('Server-1', 'Web'),
        endpoint(HOME_LABEL, 'red'),
        'PC-A までは分かるが、アプリ入口までは復元できない。',
        {
          verdict: 'ACCEPT',
          flow: 'inbound',
          expectedTarget: endpoint('PC-A', '1001'),
        },
        '内側ポートを記録していないため、PC内のどのアプリへ戻すか確定できない。',
        undefined,
        {
          title: '内側ポート不足',
          message:
            'PC-A という端末までは分かっても、1001 番のアプリ入口を特定できません。NAPT テーブルには内側ポートも必要です。',
        },
      ),
    ],
  },
  {
    id: 'day-12',
    unit: 4,
    dayNumber: 12,
    phaseId: 'internalPort',
    title: 'DAY 12: 内側ポートの記録',
    summary: 'テーブルに内側ポートを持つと、同じ PC の中の複数アプリへ正しく戻せる。',
    learningGoal: '内側ポートまで保存すればアプリ単位で復元できる。',
    availableStamps: ['red', 'blue'],
    rules: {
      columns: ['externalPort', 'destinationHost', 'destinationService', 'internalHost', 'internalPort'],
      inboundLookupKeys: ['externalPort', 'destinationHost', 'destinationService'],
    },
    runtime: {
      ordering: 'mixed',
      repeatForcedFailureUntilIncident: true,
      varianceMode: 'steady',
    },
    packets: [
      packet(
        'day-12-outbound-1001',
        'lanToWan',
        endpoint('PC-A', '1001'),
        endpoint('Server-1', 'Web'),
        'PC-A:1001 を赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-12-1001', 1, 3),
      ),
      packet(
        'day-12-outbound-1002',
        'lanToWan',
        endpoint('PC-A', '1002'),
        endpoint('Server-2', 'Web'),
        'PC-A:1002 を青で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'blue' },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-12-1002', 1, 3),
      ),
      packet(
        'day-12-inbound-1001',
        'wanToLan',
        endpoint('Server-1', 'Web'),
        endpoint(HOME_LABEL, 'red'),
        '赤の返信を PC-A:1001 に戻す。',
        { verdict: 'ACCEPT', flow: 'inbound', expectedTarget: endpoint('PC-A', '1001') },
        undefined,
        undefined,
        undefined,
        { ...repeatGroup('day-12-1001', 1, 3), arrivalDelayActions: 2 },
      ),
      packet(
        'day-12-inbound-1002',
        'wanToLan',
        endpoint('Server-2', 'Web'),
        endpoint(HOME_LABEL, 'blue'),
        '青の返信を PC-A:1002 に戻す。',
        { verdict: 'ACCEPT', flow: 'inbound', expectedTarget: endpoint('PC-A', '1002') },
        undefined,
        undefined,
        undefined,
        { ...repeatGroup('day-12-1002', 1, 3), arrivalDelayActions: 1 },
      ),
    ],
  },
  {
    id: 'day-13',
    unit: 4,
    dayNumber: 13,
    phaseId: 'internalPort',
    title: 'DAY 13: 内側ポート付きの拒否',
    summary: '端末は同じでも、記録していない色や行の返信は受け入れない。',
    learningGoal: '内側ポートを持っていても、対応表にない返信は拒否する。',
    availableStamps: ['red'],
    rules: {
      columns: ['externalPort', 'destinationHost', 'destinationService', 'internalHost', 'internalPort'],
      inboundLookupKeys: ['externalPort', 'destinationHost', 'destinationService'],
    },
    runtime: {
      ordering: 'mixed',
      repeatForcedFailureUntilIncident: false,
      minCycles: 2,
      maxCycles: 4,
      varianceMode: 'rising',
    },
    packets: [
      packet(
        'day-13-outbound-1001',
        'lanToWan',
        endpoint('PC-A', '1001'),
        endpoint('Server-1', 'Web'),
        'PC-A:1001 を赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        undefined,
        undefined,
        oncePerSession(repeatGroup('day-13-main', 2, 4)),
      ),
      packet(
        'day-13-inbound-bad',
        'wanToLan',
        endpoint('Server-2', 'Web'),
        endpoint(HOME_LABEL, 'red'),
        '赤でも Server-2 の返信は要求していないので拒否する。',
        { verdict: 'REJECT', reason: '宛先ホストが登録済みの行と一致しないから。', reasonCode: 'destinationHostMismatch' },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-13-reject', 2, 4),
      ),
      packet(
        'day-13-inbound-noise-server-3',
        'wanToLan',
        endpoint('Server-3', 'Web'),
        endpoint(HOME_LABEL, 'red'),
        'たまに別の Web 返信も紛れ込む。これも要求していないので拒否する。',
        { verdict: 'REJECT', reason: '宛先ホストが登録済みの行と一致しないから。', reasonCode: 'destinationHostMismatch' },
        undefined,
        undefined,
        undefined,
        variantTraffic('day-13-noise', 'server-3', optionalTraffic(0.45, repeatGroup('day-13-noise-copy', 1, 2))),
      ),
      packet(
        'day-13-inbound-noise-server-4',
        'wanToLan',
        endpoint('Server-4', 'Web'),
        endpoint(HOME_LABEL, 'red'),
        '別の日は別の Web 返信が紛れ込むこともある。これも要求していないので拒否する。',
        { verdict: 'REJECT', reason: '宛先ホストが登録済みの行と一致しないから。', reasonCode: 'destinationHostMismatch' },
        undefined,
        undefined,
        undefined,
        variantTraffic('day-13-noise', 'server-4', optionalTraffic(0.45, repeatGroup('day-13-noise-copy', 1, 2))),
      ),
    ],
  },
  {
    id: 'day-14',
    unit: 5,
    dayNumber: 14,
    phaseId: 'externalUniqueness',
    title: 'DAY 14: 外側一意性',
    summary: '同じ識別キーの通信には、別の色を割り当てて外側一意性を守る。',
    learningGoal: '同じ照合キーが重なる時は、外側ポートを再利用してはいけない。',
    availableStamps: ['red', 'blue'],
    rules: {
      columns: ['externalPort', 'destinationHost', 'destinationService', 'internalHost', 'internalPort'],
      inboundLookupKeys: ['externalPort', 'destinationHost', 'destinationService'],
    },
    packets: [
      packet(
        'day-14-outbound-1001',
        'lanToWan',
        endpoint('PC-A', '1001'),
        endpoint('Server-1', 'Web'),
        '最初の通信は赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
      ),
      packet(
        'day-14-outbound-1002',
        'lanToWan',
        endpoint('PC-A', '1002'),
        endpoint('Server-1', 'Web'),
        '同じ相手・同じサービスなので、赤は衝突する。別の色を使う。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'blue' },
      ),
      packet(
        'day-14-inbound-1001',
        'wanToLan',
        endpoint('Server-1', 'Web'),
        endpoint(HOME_LABEL, 'red'),
        '赤の返信を PC-A:1001 に戻す。',
        { verdict: 'ACCEPT', flow: 'inbound', expectedTarget: endpoint('PC-A', '1001') },
      ),
      packet(
        'day-14-inbound-1002',
        'wanToLan',
        endpoint('Server-1', 'Web'),
        endpoint(HOME_LABEL, 'blue'),
        '青の返信を PC-A:1002 に戻す。',
        { verdict: 'ACCEPT', flow: 'inbound', expectedTarget: endpoint('PC-A', '1002') },
      ),
    ],
  },
  {
    id: 'day-15',
    unit: 5,
    dayNumber: 15,
    phaseId: 'externalUniqueness',
    title: 'DAY 15: 再利用できる条件',
    summary: 'サービスが違えば、同じ色でも別の通信として安全に再利用できる。',
    learningGoal: '外側ポートの再利用可否は、照合キー全体の組み合わせで決まる。',
    availableStamps: ['red'],
    rules: {
      columns: ['externalPort', 'destinationHost', 'destinationService', 'internalHost', 'internalPort'],
      inboundLookupKeys: ['externalPort', 'destinationHost', 'destinationService'],
    },
    runtime: {
      minCycles: 1,
      maxCycles: 2,
      varianceMode: 'rising',
    },
    packets: [
      packet(
        'day-15-outbound-web',
        'lanToWan',
        endpoint('PC-A', '1001'),
        endpoint('Server-1', 'Web'),
        'Web 向け通信を赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-15-web', 1, 3),
      ),
      packet(
        'day-15-outbound-game',
        'lanToWan',
        endpoint('PC-A', '1002'),
        endpoint('Server-1', 'Game'),
        'サービスが違うので、同じ赤を再利用できる。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-15-game', 1, 3),
      ),
      packet(
        'day-15-inbound-web',
        'wanToLan',
        endpoint('Server-1', 'Web'),
        endpoint(HOME_LABEL, 'red'),
        '赤かつ Web の返信を PC-A:1001 に戻す。',
        { verdict: 'ACCEPT', flow: 'inbound', expectedTarget: endpoint('PC-A', '1001') },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-15-web', 1, 3),
      ),
      packet(
        'day-15-inbound-game',
        'wanToLan',
        endpoint('Server-1', 'Game'),
        endpoint(HOME_LABEL, 'red'),
        '赤かつ Game の返信を PC-A:1002 に戻す。',
        { verdict: 'ACCEPT', flow: 'inbound', expectedTarget: endpoint('PC-A', '1002') },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-15-game', 1, 3),
      ),
    ],
  },
  {
    id: 'day-16',
    unit: 5,
    dayNumber: 16,
    phaseId: 'externalUniqueness',
    title: 'DAY 16: 一意性を守った拒否',
    summary: '色を再利用できる条件を外れた返信は、迷わず拒否する。',
    learningGoal: '同じ色でもサービスが違えば別物なので、不一致は REJECT する。',
    availableStamps: ['red'],
    rules: {
      columns: ['externalPort', 'destinationHost', 'destinationService', 'internalHost', 'internalPort'],
      inboundLookupKeys: ['externalPort', 'destinationHost', 'destinationService'],
    },
    runtime: {
      minCycles: 2,
      maxCycles: 4,
      varianceMode: 'rising',
    },
    packets: [
      packet(
        'day-16-outbound-web',
        'lanToWan',
        endpoint('PC-A', '1001'),
        endpoint('Server-1', 'Web'),
        'Web 向け通信を赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        undefined,
        undefined,
        oncePerSession(repeatGroup('day-16-web', 1, 3)),
      ),
      packet(
        'day-16-outbound-game',
        'lanToWan',
        endpoint('PC-A', '1002'),
        endpoint('Server-1', 'Game'),
        'Game 向け通信も赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        undefined,
        undefined,
        oncePerSession(repeatGroup('day-16-game', 1, 3)),
      ),
      packet(
        'day-16-inbound-bad',
        'wanToLan',
        endpoint('Server-1', 'Chat'),
        endpoint(HOME_LABEL, 'red'),
        'Chat 用の記録はないので拒否する。',
        { verdict: 'REJECT', reason: 'サービスが一致する登録行が存在しないから。', reasonCode: 'destinationServiceMismatch' },
        undefined,
        undefined,
        undefined,
        repeatGroup('day-16-reject', 2, 4),
      ),
      packet(
        'day-16-inbound-noise-mail',
        'wanToLan',
        endpoint('Server-1', 'Mail'),
        endpoint(HOME_LABEL, 'red'),
        'たまに Mail の返信も紛れ込む。これも記録がないので拒否する。',
        { verdict: 'REJECT', reason: 'サービスが一致する登録行が存在しないから。', reasonCode: 'destinationServiceMismatch' },
        undefined,
        undefined,
        undefined,
        variantTraffic('day-16-noise', 'mail', optionalTraffic(0.5, repeatGroup('day-16-noise-copy', 1, 2))),
      ),
      packet(
        'day-16-inbound-noise-voice',
        'wanToLan',
        endpoint('Server-1', 'Voice'),
        endpoint(HOME_LABEL, 'red'),
        '別の回では Voice の返信が紛れ込む。これも記録がないので拒否する。',
        { verdict: 'REJECT', reason: 'サービスが一致する登録行が存在しないから。', reasonCode: 'destinationServiceMismatch' },
        undefined,
        undefined,
        undefined,
        variantTraffic('day-16-noise', 'voice', optionalTraffic(0.5, repeatGroup('day-16-noise-copy', 1, 2))),
      ),
    ],
  },
  {
    id: 'day-17',
    unit: 6,
    dayNumber: 17,
    phaseId: 'protocolSplit',
    title: 'DAY 17: プロトコル未区別の破綻',
    summary: '同じ色・同じ宛先・同じサービスでも、TCP と UDP を見ないと区別できない。',
    learningGoal: 'プロトコルも NAPT の識別キーに含める必要がある。',
    availableStamps: ['red'],
    rules: {
      columns: ['externalPort', 'destinationHost', 'destinationService', 'internalHost', 'internalPort'],
      inboundLookupKeys: ['externalPort', 'destinationHost', 'destinationService'],
    },
    packets: [
      packet(
        'day-17-outbound-tcp',
        'lanToWan',
        endpoint('PC-A', '1001'),
        endpoint('Server-1', 'Game'),
        'TCP の Game 通信を赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        'TCP',
      ),
      packet(
        'day-17-outbound-udp',
        'lanToWan',
        endpoint('PC-B', '2001'),
        endpoint('Server-1', 'Game'),
        'UDP の Game 通信も赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        'UDP',
      ),
      packet(
        'day-17-collapse',
        'wanToLan',
        endpoint('Server-1', 'Game'),
        endpoint(HOME_LABEL, 'red'),
        '返信は来たが、TCP と UDP を見ないと区別できない。',
        {
          verdict: 'ACCEPT',
          flow: 'inbound',
          expectedTarget: endpoint('PC-A', '1001'),
        },
        'プロトコル列がまだないため、同じサービスの TCP/UDP が重なる。',
        'TCP',
        {
          title: 'プロトコル未区別',
          message:
            '赤・Server-1・Game までは一致しますが、TCP と UDP を見分ける列がありません。最後の識別キーとして protocol が必要です。',
        },
      ),
    ],
  },
  {
    id: 'day-18',
    unit: 6,
    dayNumber: 18,
    phaseId: 'protocolSplit',
    title: 'DAY 18: プロトコル列の完成',
    summary: 'TCP / UDP を識別キーに含めると、同じサービスでも安全に共存できる。',
    learningGoal: '最終的な NAPT は protocol まで見て戻り先を決める。',
    availableStamps: ['red'],
    rules: {
      columns: ['protocol', 'externalPort', 'destinationHost', 'destinationService', 'internalHost', 'internalPort'],
      inboundLookupKeys: ['protocol', 'externalPort', 'destinationHost', 'destinationService'],
    },
    runtime: {
      minCycles: 1,
      maxCycles: 2,
      varianceMode: 'rising',
    },
    packets: [
      packet(
        'day-18-outbound-tcp',
        'lanToWan',
        endpoint('PC-A', '1001'),
        endpoint('Server-1', 'Game'),
        'TCP の Game 通信を赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        'TCP',
        undefined,
        repeatGroup('day-18-tcp', 1, 3),
      ),
      packet(
        'day-18-outbound-udp',
        'lanToWan',
        endpoint('PC-B', '2001'),
        endpoint('Server-1', 'Game'),
        'UDP の Game 通信も同じ赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        'UDP',
        undefined,
        repeatGroup('day-18-udp', 1, 3),
      ),
      packet(
        'day-18-inbound-tcp',
        'wanToLan',
        endpoint('Server-1', 'Game'),
        endpoint(HOME_LABEL, 'red'),
        'TCP の返信を PC-A:1001 に戻す。',
        { verdict: 'ACCEPT', flow: 'inbound', expectedTarget: endpoint('PC-A', '1001') },
        undefined,
        'TCP',
        undefined,
        { ...repeatGroup('day-18-tcp', 1, 3), arrivalDelayActions: 2 },
      ),
      packet(
        'day-18-inbound-udp',
        'wanToLan',
        endpoint('Server-1', 'Game'),
        endpoint(HOME_LABEL, 'red'),
        'UDP の返信を PC-B:2001 に戻す。',
        { verdict: 'ACCEPT', flow: 'inbound', expectedTarget: endpoint('PC-B', '2001') },
        undefined,
        'UDP',
        undefined,
        { ...repeatGroup('day-18-udp', 1, 3), arrivalDelayActions: 2 },
      ),
    ],
  },
  {
    id: 'day-19',
    unit: 6,
    dayNumber: 19,
    phaseId: 'protocolSplit',
    title: 'DAY 19: プロトコル不一致の拒否',
    summary: '色も宛先も同じでも、プロトコルが違う返信は通してはいけない。',
    learningGoal: 'TCP / UDP の不一致は REJECT で止める。',
    availableStamps: ['red'],
    rules: {
      columns: ['protocol', 'externalPort', 'destinationHost', 'destinationService', 'internalHost', 'internalPort'],
      inboundLookupKeys: ['protocol', 'externalPort', 'destinationHost', 'destinationService'],
    },
    runtime: {
      minCycles: 2,
      maxCycles: 4,
      varianceMode: 'full',
    },
    packets: [
      packet(
        'day-19-outbound-tcp',
        'lanToWan',
        endpoint('PC-A', '1001'),
        endpoint('Server-1', 'Game'),
        'TCP の Game 通信を赤で登録する。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        'TCP',
        undefined,
        oncePerSession(repeatGroup('day-19-main', 2, 4)),
      ),
      packet(
        'day-19-inbound-bad',
        'wanToLan',
        endpoint('Server-1', 'Game'),
        endpoint(HOME_LABEL, 'red'),
        '見た目は似ていても UDP の返信は要求していないので拒否する。',
        { verdict: 'REJECT', reason: 'プロトコルがテーブル記録と一致しないから。', reasonCode: 'protocolMismatch' },
        undefined,
        'UDP',
        undefined,
        { ...repeatGroup('day-19-reject', 2, 4), arrivalDelayActions: 1 },
      ),
      packet(
        'day-19-inbound-noise-server-1',
        'wanToLan',
        endpoint('Server-1', 'Game'),
        endpoint(HOME_LABEL, 'red'),
        'たまにもう一本 UDP の返信も来る。これも TCP の記録とは一致しない。',
        { verdict: 'REJECT', reason: 'プロトコルがテーブル記録と一致しないから。', reasonCode: 'protocolMismatch' },
        undefined,
        'UDP',
        undefined,
        variantTraffic(
          'day-19-noise',
          'server-1',
          optionalTraffic(0.55, { ...repeatGroup('day-19-noise-copy', 1, 2), arrivalDelayActions: 2 }),
        ),
      ),
      packet(
        'day-19-inbound-noise-server-2',
        'wanToLan',
        endpoint('Server-2', 'Game'),
        endpoint(HOME_LABEL, 'red'),
        '別の回では別ホストからも UDP の返信が来る。これも一致しない。',
        { verdict: 'REJECT', reason: 'プロトコルがテーブル記録と一致しないから。', reasonCode: 'protocolMismatch' },
        undefined,
        'UDP',
        undefined,
        variantTraffic(
          'day-19-noise',
          'server-2',
          optionalTraffic(0.55, { ...repeatGroup('day-19-noise-copy', 1, 2), arrivalDelayActions: 2 }),
        ),
      ),
    ],
  },
  {
    id: 'day-20',
    unit: 7,
    dayNumber: 20,
    phaseId: 'timeoutLifecycle',
    title: 'DAY 20: 自動タイムアウト',
    summary: '設備はすでに満杯で動いている。放置された古い通信が切れると、ようやく色を再利用できる。',
    learningGoal: '既存行のタイムアウトを待って、空いた色を新しい通信へ回す。',
    availableStamps: PORT_STAMP_IDS,
    rules: {
      columns: ['protocol', 'externalPort', 'destinationHost', 'destinationService', 'internalHost', 'internalPort'],
      inboundLookupKeys: ['protocol', 'externalPort', 'destinationHost', 'destinationService'],
      portReusePolicy: 'exclusive',
    },
    initialTableEntries: [
      {
        ...seededEntry('red', 'PC-01', 'Server-01', 'Web', 6),
        backgroundFlow: backgroundFlow(1, 2, {
          firstDelayActions: 2,
          intervalActions: 2,
          waitBudgetActions: 2,
          prompt: 'Server-01 から古い Web の返信が届いた。まだ赤の行も稼働中だ。',
        }),
      },
      {
        ...seededEntry('blue', 'PC-02', 'Server-02', 'Game', 3, 'UDP', '2002'),
        backgroundFlow: backgroundFlow(2, 3, {
          firstDelayActions: 1,
          intervalActions: 1,
          waitBudgetActions: 2,
          prompt: 'Server-02 から古い UDP の返信が届いた。青の行はまだ切れていない。',
        }),
      },
      seededEntry('green', 'PC-03', 'Server-03', 'Mail', 6),
      seededEntry('yellow', 'PC-04', 'Server-04', 'Chat', 6),
      seededEntry('orange', 'PC-05', 'Server-05', 'Web', 6),
      seededEntry('purple', 'PC-06', 'Server-06', 'Game', 6),
      seededEntry('cyan', 'PC-07', 'Server-07', 'Mail', 6),
      seededEntry('pink', 'PC-08', 'Server-08', 'Chat', 6),
      seededEntry('lime', 'PC-09', 'Server-09', 'Web', 6),
      seededEntry('amber', 'PC-10', 'Server-10', 'Game', 6),
      seededEntry('teal', 'PC-11', 'Server-11', 'Mail', 6),
      seededEntry('indigo', 'PC-12', 'Server-12', 'Chat', 6),
      seededEntry('rose', 'PC-13', 'Server-13', 'Web', 6),
      seededEntry('sky', 'PC-14', 'Server-14', 'Game', 6),
      seededEntry('emerald', 'PC-15', 'Server-15', 'Mail', 6),
      seededEntry('slate', 'PC-16', 'Server-16', 'Chat', 6),
    ],
    runtime: {
      ordering: 'returnsMayLead',
      repeatForcedFailureUntilIncident: false,
    },
    shiftGoal: {
      requiredSuccesses: 4,
      maxIncidents: 1,
      maxActions: 10,
      clearMessage: '古い行のタイムアウトを待ちながら、新しい通信も安全に通し切った。',
      failureMessage: 'タイムアウト運用の間に事故が増えすぎたか、必要な処理数に届かなかった。',
    },
    packets: [
      packet(
        'day-20-outbound-new',
        'lanToWan',
        endpoint('PC-17', '2017'),
        endpoint('Server-17', 'Game'),
        '今は全色使用中だ。青の行が切れるまでは送れない。様子を見ながら、空いた瞬間に青で通す。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'blue' },
        undefined,
        'UDP',
        undefined,
        { waitBudgetActions: 5 },
      ),
      packet(
        'day-20-reject-1',
        'wanToLan',
        endpoint('Unknown', 'Game'),
        endpoint(HOME_LABEL, 'blue'),
        '関係のない返信が来ても、設備側では古い行の残り時間が減っていく。',
        { verdict: 'REJECT', reason: '送信元が登録済みの通信と一致しないから。', reasonCode: 'sourceHostMismatch' },
        undefined,
        'UDP',
        undefined,
        { minCopies: 1, maxCopies: 1, arrivalDelayActions: 1, waitBudgetActions: 3 },
      ),
      packet(
        'day-20-reject-2',
        'wanToLan',
        endpoint('Unknown', 'Game'),
        endpoint(HOME_LABEL, 'blue'),
        'もう一本ノイズが届く。これを捌く頃には、古い青の行が切れているはずだ。',
        { verdict: 'REJECT', reason: '送信元が登録済みの通信と一致しないから。', reasonCode: 'sourceHostMismatch' },
        undefined,
        'UDP',
        undefined,
        { minCopies: 1, maxCopies: 1, arrivalDelayActions: 2, waitBudgetActions: 2 },
      ),
    ],
  },
  {
    id: 'day-21',
    unit: 7,
    dayNumber: 21,
    phaseId: 'manualClose',
    title: 'DAY 21: 手動クローズ',
    summary: '切れるまで待てない通信もある。手動で古い行を閉じれば、その色をすぐ使い回せる。',
    learningGoal: '待てない時は通信を手動で終了し、色を即座に再利用する。',
    availableStamps: ['red'],
    rules: {
      columns: ['protocol', 'externalPort', 'destinationHost', 'destinationService', 'internalHost', 'internalPort'],
      inboundLookupKeys: ['protocol', 'externalPort', 'destinationHost', 'destinationService'],
      portReusePolicy: 'exclusive',
    },
    initialTableEntries: [
      {
        ...seededEntry('red', 'PC-A', 'Server-1', 'Web', 9, 'TCP', '1001'),
        backgroundFlow: backgroundFlow(2, 3, {
          firstDelayActions: 1,
          intervalActions: 1,
          waitBudgetActions: 2,
          prompt: 'Server-1 から古い Web の返信が届いた。赤の古い行を閉じない限り続く。',
        }),
      },
    ],
    shiftGoal: {
      requiredSuccesses: 3,
      requiredCloses: 1,
      maxIncidents: 1,
      maxActions: 8,
      clearMessage: '古い行を手動で閉じ、赤の再利用まで含めて今日の運用を捌き切った。',
      failureMessage: 'クローズ操作か必要処理数を満たす前に、今日の運用を維持できなかった。',
    },
    packets: [
      packet(
        'day-21-outbound-second',
        'lanToWan',
        endpoint('PC-A', '1002'),
        endpoint('Server-2', 'Mail'),
        '赤の古い通信はまだ残っている。この個包は待たせず、古い行を閉じてから赤を割り当て直す。',
        { verdict: 'ACCEPT', flow: 'outbound', requiredStampId: 'red' },
        undefined,
        'TCP',
        undefined,
        { waitBudgetActions: 3 },
      ),
      packet(
        'day-21-inbound-second',
        'wanToLan',
        endpoint('Server-2', 'Mail'),
        endpoint(HOME_LABEL, 'red'),
        '閉じた後に登録し直した赤の返信を、PC-A:1002 に戻す。',
        { verdict: 'ACCEPT', flow: 'inbound', expectedTarget: endpoint('PC-A', '1002') },
        undefined,
        'TCP',
        undefined,
        { arrivalDelayActions: 2, waitBudgetActions: 2 },
      ),
    ],
  },
  {
    id: 'day-22',
    unit: 8,
    dayNumber: 22,
    phaseId: 'portExhaustion',
    title: 'DAY 22: ポート枯渇',
    summary: 'まだ閉じられない通信で設備が満杯なら、新しい依頼を断るのも運用判断になる。',
    learningGoal: '空きがない時は無理に通さず、REJECT で設備を守る。',
    availableStamps: ['red', 'blue'],
    rules: {
      columns: ['protocol', 'externalPort', 'destinationHost', 'destinationService', 'internalHost', 'internalPort'],
      inboundLookupKeys: ['protocol', 'externalPort', 'destinationHost', 'destinationService'],
      portReusePolicy: 'exclusive',
    },
    initialTableEntries: [
      {
        ...seededEntry('red', 'PC-A', 'Server-1', 'Web', 9, 'TCP', '1001'),
        backgroundFlow: backgroundFlow(2, 3, {
          firstDelayActions: 1,
          intervalActions: 1,
          waitBudgetActions: 2,
          prompt: 'Server-1 から古い Web の返信が届いた。赤の設備はまだ使用中だ。',
        }),
      },
      {
        ...seededEntry('blue', 'PC-B', 'Server-2', 'Game', 9, 'UDP', '2001'),
        backgroundFlow: backgroundFlow(2, 3, {
          firstDelayActions: 1,
          intervalActions: 2,
          waitBudgetActions: 2,
          prompt: 'Server-2 から古い UDP の返信が届いた。青の設備もまだ使用中だ。',
        }),
      },
    ],
    runtime: {
      minCycles: 2,
      maxCycles: 4,
      varianceMode: 'full',
    },
    shiftGoal: {
      requiredRejects: 3,
      maxIncidents: 0,
      maxActions: 6,
      clearMessage: '空きがない状況で無理に通さず、設備を守り切った。',
      failureMessage: '拒否判断が足りないか、事故を出して設備を守れなかった。',
    },
    packets: [
      packet(
        'day-22-outbound-full',
        'lanToWan',
        endpoint('PC-C', '3001'),
        endpoint('Server-3', 'Chat'),
        '赤も青も使用中で、どちらもまだ閉じられない。新しい通信は断って設備を守る。',
        { verdict: 'REJECT', reason: '利用可能な外側ポートが残っていないから。', reasonCode: 'portExhausted' },
        undefined,
        'TCP',
        undefined,
        { ...repeatGroup('day-22-full', 1, 2), waitBudgetActions: 3 },
      ),
      packet(
        'day-22-outbound-noise-mail',
        'lanToWan',
        endpoint('PC-D', '3002'),
        endpoint('Server-4', 'Mail'),
        '混雑している日は別の新規通信も来る。空きがなければこれも拒否する。',
        { verdict: 'REJECT', reason: '利用可能な外側ポートが残っていないから。', reasonCode: 'portExhausted' },
        undefined,
        'TCP',
        undefined,
        variantTraffic(
          'day-22-noise',
          'mail',
          optionalTraffic(0.5, { ...repeatGroup('day-22-noise-copy', 1, 2), waitBudgetActions: 2 }),
        ),
      ),
      packet(
        'day-22-outbound-noise-chat',
        'lanToWan',
        endpoint('PC-E', '3003'),
        endpoint('Server-5', 'Chat'),
        '別の回では Chat の新規通信が来る。空きがなければこれも拒否する。',
        { verdict: 'REJECT', reason: '利用可能な外側ポートが残っていないから。', reasonCode: 'portExhausted' },
        undefined,
        'TCP',
        undefined,
        variantTraffic(
          'day-22-noise',
          'chat',
          optionalTraffic(0.5, { ...repeatGroup('day-22-noise-copy', 1, 2), waitBudgetActions: 2 }),
        ),
      ),
    ],
  },
];

export const scenarioDayIds = scenarioDays.map((day) => day.id);

export const scenarioDayMap = Object.fromEntries(
  scenarioDays.map((day) => [day.id, day]),
) as Record<ScenarioDay['id'], ScenarioDay>;

for (let index = 0; index < scenarioDays.length; index += 1) {
  const current = scenarioDays[index];
  const next = scenarioDays[index + 1]?.id ?? null;

  current.availableVerdicts = current.availableVerdicts ?? ['ACCEPT', 'REJECT'];

  current.flow = {
    nextOnClear: current.flow?.nextOnClear ?? next,
    nextOnFailure: current.flow?.nextOnFailure ?? next,
  };
}
