import {
  advanceToNextDay,
  beginCurrentDay,
  commitWorkbenchDispatch,
  chooseRouteTarget,
  chooseStamp,
  chooseTableEntry,
  closeSelectedTableEntry,
  dropStampSelection,
  inspectRunArchive,
  pullPacketToWorkbench,
  replayCurrentDay,
  shelveWorkbenchPacket,
  setDispatchIntent,
  setReferenceTab,
  setReferenceOpen,
  setDestinationHostFilter,
  setExternalPortFilter,
  setTableSortMode,
  startCampaign,
  waitOneTurn,
} from '../gameSlice'
import {
  selectArchiveList,
  selectAuditLog,
  selectCampaignSummary,
  selectCatalogSummary,
  selectCurrentDay,
  selectCurrentActionChecklist,
  selectCurrentUnitReference,
  selectDraftRouteTargetSummary,
  selectDraftStampSummary,
  selectDraftTableEntrySummary,
  selectDayProgress,
  selectDayRuntimeSummary,
  selectFeedback,
  selectGameScreen,
  selectInspectedRunArchive,
  selectIncomingPacketPreview,
  selectIncomingPacketPreviews,
  selectUpcomingPacketCount,
  selectIsArchiveInspection,
  selectLastResolution,
  selectLatestActionResult,
  selectMatchingTableEntryIds,
  selectPacketPresentation,
  selectPacketRewritePreview,
  selectProgressIntegrityReport,
  selectReferenceSummary,
  selectReferenceTab,
  selectReferenceOpen,
  selectRelevantGlossaryEntries,
  selectRecentActionSlips,
  selectResolutionDossier,
  selectResolutionUnlockSummary,
  selectRunArchiveSummary,
  selectRunHistorySummary,
  selectRouteSlipTargets,
  selectAppliedRouteTargetSummary,
  selectAppliedStampSummary,
  selectAppliedTableEntryId,
  selectAvailableVerdicts,
  selectSelectedTableEntrySummary,
  selectSelectedTableEntryId,
  selectSessionIntegrityReport,
  selectShiftGoalSummary,
  selectStampOptions,
  selectTableColumns,
  selectTableFeatureFlags,
  selectTableFilterOptions,
  selectTableRows,
  selectTableUsageSummary,
  selectTableViewState,
  selectTrafficBoard,
  selectWorkbenchPlacement,
  selectWorkbenchStatus,
  selectWorkbenchDispatchIntent,
} from '../selectors'
import type { StampId } from '../types'
import { useAppDispatch, useAppSelector } from '../../../app/hooks'

export function useGameViewModel() {
  const dispatch = useAppDispatch()

  return {
    screen: useAppSelector(selectGameScreen),
    day: useAppSelector(selectCurrentDay),
    unitReference: useAppSelector(selectCurrentUnitReference),
    packet: useAppSelector(selectPacketPresentation),
    availableVerdicts: useAppSelector(selectAvailableVerdicts),
    incomingPacket: useAppSelector(selectIncomingPacketPreview),
    incomingPackets: useAppSelector(selectIncomingPacketPreviews),
    upcomingPacketCount: useAppSelector(selectUpcomingPacketCount),
    packetRewritePreview: useAppSelector(selectPacketRewritePreview),
    workbenchPlacement: useAppSelector(selectWorkbenchPlacement),
    workbenchStatus: useAppSelector(selectWorkbenchStatus),
    workbenchDispatchIntent: useAppSelector(selectWorkbenchDispatchIntent),
    trafficBoard: useAppSelector(selectTrafficBoard),
    progress: useAppSelector(selectDayProgress),
    dayRuntimeSummary: useAppSelector(selectDayRuntimeSummary),
    shiftGoalSummary: useAppSelector(selectShiftGoalSummary),
    feedback: useAppSelector(selectFeedback),
    latestActionResult: useAppSelector(selectLatestActionResult),
    recentActionSlips: useAppSelector(selectRecentActionSlips),
    resolution: useAppSelector(selectLastResolution),
    resolutionDossier: useAppSelector(selectResolutionDossier),
    resolutionUnlockSummary: useAppSelector(selectResolutionUnlockSummary),
    isArchiveInspection: useAppSelector(selectIsArchiveInspection),
    inspectedRunArchive: useAppSelector(selectInspectedRunArchive),
    archiveList: useAppSelector(selectArchiveList),
    runArchiveSummary: useAppSelector(selectRunArchiveSummary),
    runHistorySummary: useAppSelector(selectRunHistorySummary),
    sessionIntegrity: useAppSelector(selectSessionIntegrityReport),
    progressIntegrity: useAppSelector(selectProgressIntegrityReport),
    referenceSummary: useAppSelector(selectReferenceSummary),
    actionChecklist: useAppSelector(selectCurrentActionChecklist),
    glossaryEntries: useAppSelector(selectRelevantGlossaryEntries),
    referenceTab: useAppSelector(selectReferenceTab),
    referenceOpen: useAppSelector(selectReferenceOpen),
    stampOptions: useAppSelector(selectStampOptions),
    routeSlipTargets: useAppSelector(selectRouteSlipTargets),
    draftRouteTargetSummary: useAppSelector(selectDraftRouteTargetSummary),
    draftStampSummary: useAppSelector(selectDraftStampSummary),
    appliedRouteTargetSummary: useAppSelector(selectAppliedRouteTargetSummary),
    appliedStampSummary: useAppSelector(selectAppliedStampSummary),
    columns: useAppSelector(selectTableColumns),
    tableFeatureFlags: useAppSelector(selectTableFeatureFlags),
    rows: useAppSelector(selectTableRows),
    tableUsageSummary: useAppSelector(selectTableUsageSummary),
    matchingEntryIds: useAppSelector(selectMatchingTableEntryIds),
    selectedEntryId: useAppSelector(selectSelectedTableEntryId),
    appliedEntryId: useAppSelector(selectAppliedTableEntryId),
    draftEntrySummary: useAppSelector(selectDraftTableEntrySummary),
    selectedEntrySummary: useAppSelector(selectSelectedTableEntrySummary),
    auditLog: useAppSelector(selectAuditLog),
    campaignSummary: useAppSelector(selectCampaignSummary),
    catalogSummary: useAppSelector(selectCatalogSummary),
    tableView: useAppSelector(selectTableViewState),
    tableFilterOptions: useAppSelector(selectTableFilterOptions),
    actions: {
      startCampaign: () => dispatch(startCampaign()),
      beginCurrentDay: () => dispatch(beginCurrentDay()),
      advanceToNextDay: () => dispatch(advanceToNextDay()),
      replayCurrentDay: () => dispatch(replayCurrentDay()),
      shelveWorkbenchPacket: () => dispatch(shelveWorkbenchPacket()),
      inspectRunArchive: (runId: string) => dispatch(inspectRunArchive(runId)),
      pullPacketToWorkbench: (packetRuntimeId?: string) => dispatch(pullPacketToWorkbench(packetRuntimeId)),
      chooseRouteTarget: (routeTargetId: string) => dispatch(chooseRouteTarget(routeTargetId)),
      chooseStamp: (stampId: StampId) => dispatch(chooseStamp(stampId)),
      waitOneTurn: () => dispatch(waitOneTurn()),
      setDispatchIntent: (intent: 'ACCEPT' | 'REJECT') => dispatch(setDispatchIntent(intent)),
      commitWorkbenchDispatch: () => dispatch(commitWorkbenchDispatch()),
      dropStampSelection: () => dispatch(dropStampSelection()),
      chooseTableEntry: (entryId: string) => dispatch(chooseTableEntry(entryId)),
      closeSelectedTableEntry: () => dispatch(closeSelectedTableEntry()),
      setReferenceTab: (tab: 'summary' | 'actions' | 'glossary') => dispatch(setReferenceTab(tab)),
      setReferenceOpen: (isOpen: boolean) => dispatch(setReferenceOpen(isOpen)),
      setSortMode: (mode: 'oldest' | 'newest' | 'remainingTime') => dispatch(setTableSortMode(mode)),
      setExternalPortFilter: (value: 'all' | StampId) => dispatch(setExternalPortFilter(value)),
      setDestinationHostFilter: (value: string) => dispatch(setDestinationHostFilter(value)),
    },
  }
}
